[package]
name = "mf2lsp"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lsp-server = "0.7.6"
lsp-types = "0.97.0"
mf2-parser = { path = "../parser" }
serde_json = "1.0.119"
