[package]
name = "mf2_parser"
description = "Parser and AST definitions for MessageFormat 2"
categories = ["ast", "mf2", "parser"]
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
