[package]
name = "mf2_printer"
description = "Printer for MessageFormat 2"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mf2_parser = { path = "../parser" }
