name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  tag:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --verbose --all-targets --tests --examples --release

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings --release

      - name: Run tests
        run: cargo test --release

      - name: Zip up the release build
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: "zip -r mf2lsp-$( rustc -vV | sed -n 's|host: ||p' ).zip target/release/mf2lsp"

      - name: Upload artifacts
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        use: actions/upload-artifact@v4
        with:
          name: mf2lsp
          path: mf2lsp-*.zip

      - name: GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        use: softprops/action-gh-release@v2
        with:
          draft: true
          files: mf2lsp-*.zip
